import type { LowkeyState } from "./types";
import { dayKey } from "./types";

const minutesAgo = (m: number) => new Date(Date.now() - m * 60_000).toISOString();

/**
 * demo content for both age bands. built lazily (never at module scope) so the
 * worker never sees random/date work in global scope.
 */
export function makeSeed(): LowkeyState {
  const today = dayKey();
  const yesterday = dayKey(new Date(Date.now() - 86_400_000));

  return {
    currentUserId: null,
    profiles: [
      {
        id: "u-alfie",
        handle: "alfie",
        displayName: "alfie",
        bio: "having fun @ kebnik. no caps ever",
        avatarHue: 92,
        ageBand: "under_18",
        verificationStatus: "verified",
        verifiedProvider: "simulated_eid",
        dailyLimitMinutes: 45,
        isDemo: true,
      },
      {
        id: "u-william",
        handle: "william",
        displayName: "william",
        bio: "bla bla bla bla bla",
        avatarHue: 45,
        ageBand: "under_18",
        verificationStatus: "verified",
        verifiedProvider: "simulated_eid",
        dailyLimitMinutes: 60,
        isDemo: true,
      },
      {
        id: "u-kebnik",
        handle: "kebnik",
        displayName: "kebnik",
        bio: "skate, snacks, chill",
        avatarHue: 200,
        ageBand: "under_18",
        verificationStatus: "verified",
        verifiedProvider: "simulated_eid",
        dailyLimitMinutes: 60,
        isDemo: true,
      },
      {
        id: "u-mira",
        handle: "mira",
        displayName: "mira",
        bio: "coffee then everything else",
        avatarHue: 320,
        ageBand: "adult",
        verificationStatus: "verified",
        verifiedProvider: "mitid",
        dailyLimitMinutes: 90,
        isDemo: true,
      },
      {
        id: "u-jonas",
        handle: "jonas",
        displayName: "jonas",
        bio: "lowkey posting from copenhagen",
        avatarHue: 145,
        ageBand: "adult",
        verificationStatus: "verified",
        verifiedProvider: "mitid",
        dailyLimitMinutes: 90,
        isDemo: true,
      },
      {
        id: "u-sara",
        handle: "sara",
        displayName: "sara",
        bio: "runs slow, talks fast",
        avatarHue: 20,
        ageBand: "adult",
        verificationStatus: "verified",
        verifiedProvider: "altid",
        dailyLimitMinutes: 120,
        isDemo: true,
      },
    ],
    posts: [
      {
        id: "p-1",
        authorId: "u-alfie",
        kind: "post",
        caption: "having fun @ kebnik",
        posterHue: 92,
        mediaUrl: null,
        taggedHandle: "kebnik",
        ageBand: "under_18",
        createdAt: minutesAgo(24),
      },
      {
        id: "p-2",
        authorId: "u-william",
        kind: "post",
        caption: "at rebunk w/ @alfie",
        posterHue: 45,
        mediaUrl: null,
        taggedHandle: "alfie",
        ageBand: "under_18",
        createdAt: minutesAgo(180),
      },
      {
        id: "p-3",
        authorId: "u-william",
        kind: "video",
        caption: "bla bla bla bla bla",
        posterHue: 200,
        mediaUrl: null,
        taggedHandle: null,
        ageBand: "under_18",
        createdAt: minutesAgo(300),
      },
      {
        id: "p-4",
        authorId: "u-kebnik",
        kind: "video",
        caption: "board went one way i went the other",
        posterHue: 145,
        mediaUrl: null,
        taggedHandle: null,
        ageBand: "under_18",
        createdAt: minutesAgo(520),
      },
      {
        id: "p-5",
        authorId: "u-mira",
        kind: "post",
        caption: "third coffee, no regrets",
        posterHue: 320,
        mediaUrl: null,
        taggedHandle: null,
        ageBand: "adult",
        createdAt: minutesAgo(60),
      },
      {
        id: "p-6",
        authorId: "u-jonas",
        kind: "video",
        caption: "harbour swim in september, cold as promised",
        posterHue: 200,
        mediaUrl: null,
        taggedHandle: null,
        ageBand: "adult",
        createdAt: minutesAgo(150),
      },
      {
        id: "p-7",
        authorId: "u-sara",
        kind: "post",
        caption: "10k, walked most of it",
        posterHue: 20,
        mediaUrl: null,
        taggedHandle: null,
        ageBand: "adult",
        createdAt: minutesAgo(400),
      },
    ],
    comments: [
      {
        id: "c-1",
        postId: "p-1",
        authorId: "u-william",
        body: "no way you were there",
        createdAt: minutesAgo(20),
      },
      { id: "c-2", postId: "p-5", authorId: "u-jonas", body: "same tbh", createdAt: minutesAgo(40) },
    ],
    likes: [
      { postId: "p-1", profileId: "u-william" },
      { postId: "p-1", profileId: "u-kebnik" },
      { postId: "p-5", profileId: "u-sara" },
    ],
    follows: [
      { followerId: "u-william", followingId: "u-alfie" },
      { followerId: "u-kebnik", followingId: "u-alfie" },
      { followerId: "u-jonas", followingId: "u-mira" },
      { followerId: "u-sara", followingId: "u-mira" },
    ],
    conversations: [
      { id: "cv-1", memberIds: ["u-alfie", "u-william"], ageBand: "under_18" },
      { id: "cv-2", memberIds: ["u-alfie", "u-kebnik"], ageBand: "under_18" },
      { id: "cv-3", memberIds: ["u-mira", "u-jonas"], ageBand: "adult" },
      { id: "cv-4", memberIds: ["u-mira", "u-sara"], ageBand: "adult" },
    ],
    messages: [
      {
        id: "m-1",
        conversationId: "cv-1",
        authorId: "u-william",
        body: "wanna do something",
        createdAt: minutesAgo(50),
        readByMe: true,
      },
      {
        id: "m-2",
        conversationId: "cv-1",
        authorId: "u-alfie",
        body: "i mean",
        createdAt: minutesAgo(48),
        readByMe: true,
      },
      {
        id: "m-3",
        conversationId: "cv-1",
        authorId: "u-william",
        body: "cinema",
        createdAt: minutesAgo(45),
        readByMe: false,
      },
      {
        id: "m-4",
        conversationId: "cv-2",
        authorId: "u-kebnik",
        body: "newest message",
        createdAt: minutesAgo(120),
        readByMe: true,
      },
      {
        id: "m-5",
        conversationId: "cv-3",
        authorId: "u-jonas",
        body: "dinner thursday?",
        createdAt: minutesAgo(90),
        readByMe: false,
      },
      {
        id: "m-6",
        conversationId: "cv-4",
        authorId: "u-sara",
        body: "sending the route now",
        createdAt: minutesAgo(240),
        readByMe: true,
      },
    ],
    streaks: [
      { conversationId: "cv-1", count: 12, lastActiveDay: today },
      { conversationId: "cv-2", count: 3, lastActiveDay: yesterday },
      { conversationId: "cv-3", count: 27, lastActiveDay: today },
      { conversationId: "cv-4", count: 1, lastActiveDay: yesterday },
    ],
    usageDays: [],
  };
}
